### ISSUE TITLE
Commit failed due to multiple -m options in the command

### ISSUE THREAD

**Issue by momocow** [carloscuesta/gitmoji-cli#269]
Hello @carloscuesta!

Issue:
It seems weird that the command generated by gitmoji includes multiple `-m` options.
It is not related to any specific messages, every commit just failed with different messages.

**OS**: Windows 10
**gitmoji-cli -v**: 3.0.1
**Node version**: 12.7.0

**Error Message**:
```
$ npm run commit

> gitmoji -c

? Choose a gitmoji: �📝  - Writing docs.
? Enter the commit title [21/48]: Update changelog url.
? Enter the commit message: 
Error: Command failed with exit code 1: git commit -m :memo: Update changelog url. -m
    at makeError (<project_root>\node_modules\gitmoji-cli\node_modules\execa\lib\error.js:56:11) 
    at handlePromise (<project_root>\node_modules\gitmoji-cli\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  command: 'git commit -m :memo: Update changelog url. -m ',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'On branch master\n' +
    "Your branch is up to date with 'origin/master'.\n" +
    '\n' +
    'Changes not staged for commit:\n' +
    '\tmodified:   README.md\n' +
    '\n' +
    'no changes added to commit',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by momocow** [comment]
It works fine after I restarted vscode (also a new terminal window). 😂

**Comment by carloscuesta** [comment]
The second -m is for the commit message. If you can’t provide a reproducible example I can’t work on a fix

Thanks!
