### ISSUE TITLE
timedPromise.finally is not a function

### ISSUE THREAD

**Issue by gaoryrt** [carloscuesta/gitmoji-cli#276]
Hello @carloscuesta!

When I finished messaging `gitmoji -c`, I got such message:
`timedPromise.finally is not a function`
Issue:

0. update gitmoji-cli to v3.1.0, I didn't encounter this issue in v3.0.0
1. set `alias gac="git add . && gitmoji -c"`
2. `gac`
3. fill all the blanks and press enter

**OS**: macOS Mojave 10.14.3
**gitmoji-cli -v**: 3.1.0
**Node version**: 8.12.0

```
{ TypeError: Command failed: git rev-parse --absolute-git-dir
timedPromise.finally is not a function
    at setExitHandler (/Users/gaoryrt/.config/yarn/global/node_modules/gitmoji-cli/node_modules/execa/lib/kill.js:102:29)
    at execa (/Users/gaoryrt/.config/yarn/global/node_modules/gitmoji-cli/node_modules/execa/index.js:100:22)
    at isHookCreated (/Users/gaoryrt/.config/yarn/global/node_modules/gitmoji-cli/lib/utils/isHookCreated.js:20:34)
    at withClient (/Users/gaoryrt/.config/yarn/global/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:26:42)
    at _inquirer.default.prompt.then.answers (/Users/gaoryrt/.config/yarn/global/node_modules/gitmoji-cli/lib/commands/commit/index.js:24:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  originalMessage: 'timedPromise.finally is not a function',
  shortMessage: 'Command failed: git rev-parse --absolute-git-dir\ntimedPromise.finally is not a function',
  command: 'git rev-parse --absolute-git-dir',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
{ TypeError: Command failed: git commit -m :lipstick: update style -m
timedPromise.finally is not a function
    at setExitHandler (/Users/gaoryrt/.config/yarn/global/node_modules/gitmoji-cli/node_modules/execa/lib/kill.js:102:29)
    at execa (/Users/gaoryrt/.config/yarn/global/node_modules/gitmoji-cli/node_modules/execa/index.js:100:22)
    at withClient (/Users/gaoryrt/.config/yarn/global/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:33:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  originalMessage: 'timedPromise.finally is not a function',
  shortMessage: 'Command failed: git commit -m :lipstick: update style -m \ntimedPromise.finally is not a function',
  command: 'git commit -m :lipstick: update style -m ',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
``` 

**Error Message**:

![image](https://user-images.githubusercontent.com/5306513/72137993-d21eda80-33c6-11ea-94e9-00bcb83a0f82.png)

**Comment by carloscuesta** [comment]
Hey @gaoryrt 

Thanks for reporting the issue,

Could you run the following command to see if that is the problem ?

```
git rev-parse --absolute-git-dir
```

Can't reproduce your error 😕 

<img width="605" alt="Screenshot 2020-01-10 at 10 15 33" src="https://user-images.githubusercontent.com/7629661/72141015-48edb080-3392-11ea-8e94-34f7bea404af.png">

**Comment by carloscuesta** [comment]
Also, now that I see that you're using `node@8`, minimum required version of node for this package is 10, so that could be the problem too.

https://github.com/carloscuesta/gitmoji-cli/blob/master/package.json#L6

**Comment by gaoryrt** [comment]
No more issue when I switch to node@10, so that's it.
I use `yarn --ignore-engines` when I install `gitmoji-cli` globally to avoid warning, I think I should use `--ignore-engines` carefully.
Thank you @carloscuesta .
