### ISSUE TITLE
CLI can't query gitmoji list

### ISSUE THREAD

**Issue by Larandar** [carloscuesta/gitmoji-cli#331]
Hello @carloscuesta!

When using any command that makes a query the CLI crash with the following message.

**OS**: Ubuntu (WSL)
**gitmoji-cli -v**: 3.2.1 or 3.2.2 (--version show different version from npm)
**Node version**: 13.10.1

**Error Message**:
```
query init
Error: Total of weights cannot exceed 1
    at e.value (/usr/local/lib/node_modules/gitmoji-cli/node_modules/fuse.js/dist/fuse.js:9:3409)
    at new e (/usr/local/lib/node_modules/gitmoji-cli/node_modules/fuse.js/dist/fuse.js:9:2634)
    at filterGitmojis (/usr/local/lib/node_modules/gitmoji-cli/lib/utils/filterGitmojis.js:24:16)
    at /usr/local/lib/node_modules/gitmoji-cli/lib/commands/search/index.js:18:81
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

![image](https://user-images.githubusercontent.com/906021/76439189-50463000-63bc-11ea-91fb-513d78778ebb.png)

**Comment by carloscuesta** [comment]
Hello @Larandar seems that you have two different versions installed.

This was fixed on 3.2.2 at #329, please uninstall both versions and make sure you are using the last one

Thanks!
