### ISSUE TITLE
Command line stucks when commiting with "gitmoji -c"

### ISSUE THREAD

**Issue by xItsDanger** [carloscuesta/gitmoji-cli#332]
Hello @carloscuesta!

Hi, it's me again. I'm having some troubles when commiting with gitmoji -c. It works well untill i write the commit message. Then, it just freezes. Commiting with "git commit" with the hook works tho. I've tried "CTRL+C" and it returns some json structure i will add below.

Issue:

My logs:
```js
andres at xitsdanger in ~/Coding/Alexis on master ✗                                                   ⬆ [a1e58c7]  20:09
> gitmoji -c
? Choose a gitmoji: ✨  - Introducing new features.
? Enter the commit title [18/48]: Added love command
? Enter the commit message: Added new fun command (love)
```
But when doing "CTRL+C", this appears:
```js
andres at xitsdanger in ~/Coding/Alexis on master ✗                                                   ⬆ [a1e58c7]  20:09
> gitmoji -c
? Choose a gitmoji: ✨  - Introducing new features.
? Enter the commit title [18/48]: Added love command
? Enter the commit message: Added new fun command (love)
Error: Command failed with exit code 1: git commit -S -m ✨ Added love command -m Added new fun command (love)
? Choose a gitmoji: (Use arrow keys or type to search)
❯ 🎨  - Improving structure / format of the code. 
  ⚡️  - Improving performance. 
  🔥  - Removing code or files. 
  🐛  - Fixing a bug. 
  🚑  - Critical hotfix. 
  ✨  - Introducing new features. 
  📝  - Writing docs. 
(Move up and down to reveal more choices)
    at makeError (/home/andres/.nvm/versions/node/v12.16.1/lib/node_modules/gitmoji-cli/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/andres/.nvm/versions/node/v12.16.1/lib/node_modules/gitmoji-cli/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async withClient (/home/andres/.nvm/versions/node/v12.16.1/lib/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:33:9) {
  shortMessage: 'Command failed with exit code 1: git commit -S -m ✨ Added love command -m Added new fun command (love)',
  command: 'git commit -S -m ✨ Added love command -m Added new fun command (love)',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '? Choose a gitmoji: (Use arrow keys or type to search)\n' +
    '❯ 🎨  - Improving structure / format of the code. \n' +
    '  ⚡️  - Improving performance. \n' +
    '  🔥  - Removing code or files. \n' +
    '  🐛  - Fixing a bug. \n' +
    '  🚑  - Critical hotfix. \n' +
    '  ✨  - Introducing new features. \n' +
    '  📝  - Writing docs. \n' +
    '(Move up and down to reveal more choices)\u001b[8A\u001b[41D\u001b[54C\u001b[8B',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**OS**: Ubuntu 19.10
**gitmoji-cli -v**: 3.2.3
**Node version**: 12.16.1

**Error Message**: The error message appears above, anyways i will write it here:
```js
Error: Command failed with exit code 1: git commit -S -m ✨ Added love command -m Added new fun command (love)
? Choose a gitmoji: (Use arrow keys or type to search)
❯ 🎨  - Improving structure / format of the code. 
  ⚡️  - Improving performance. 
  🔥  - Removing code or files. 
  🐛  - Fixing a bug. 
  🚑  - Critical hotfix. 
  ✨  - Introducing new features. 
  📝  - Writing docs. 
(Move up and down to reveal more choices)
    at makeError (/home/andres/.nvm/versions/node/v12.16.1/lib/node_modules/gitmoji-cli/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/andres/.nvm/versions/node/v12.16.1/lib/node_modules/gitmoji-cli/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async withClient (/home/andres/.nvm/versions/node/v12.16.1/lib/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:33:9) {
  shortMessage: 'Command failed with exit code 1: git commit -S -m ✨ Added love command -m Added new fun command (love)',
  command: 'git commit -S -m ✨ Added love command -m Added new fun command (love)',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
```
Thanks again!

**Comment by carloscuesta** [comment]
Could be this related with #266 ? 

By the way if you're using the hook, you may find some problems if you try to commit with the `gitmoji -c` command. You have to pick one of both options.

Try to clear the hook and try again

**Comment by xItsDanger** [comment]
You were right. Removing the hook was the solution.
PD: I created an alias for adding, commiting and pushing all changes at once with gitmoji, if anybody wants to use it too just:
1. Acess you bash file (.bashrc, .zhsrc...)
2. Add this line: `alias commit="gitmoji -c && git push"`

PD: You need to have enabled the automatic git add . at the gitmoji config, if you dont want to enable it just replace that line with this `alias commit="git add . && gitmoji -c && git push"`

Thanks again!
