### ISSUE TITLE
gpg error with 3.2.3 cli version

### ISSUE THREAD

**Issue by gensjaak** [carloscuesta/gitmoji-cli#334]
Hello @carloscuesta!

I've updated gitmoji-cli to latest version this morning (3.2.3) and got this error when trying to commit.

Issue:
1. Update cli to latest version (3.2.3) at this date
2. Try to commit

**OS**: macOS Mojave 10.14.6 (18G103)
**gitmoji-cli -v**: 3.2.3
**Node version**: v12.14.1

**Error Message**:
```
> gitmoji -c
? Choose a gitmoji: 🎉  - Initial commit.
? Enter the commit title [33/48]: Base of project with new codebase
? Enter the commit message:
Error: Command failed with exit code 128: git commit -S -m 🎉 Base of project with new codebase -m
error: gpg failed to sign the data
fatal: failed to write commit object
    at makeError (/Users/username/.config/yarn/global/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/username/.config/yarn/global/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async withClient (/Users/username/.config/yarn/global/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:33:9) {
  shortMessage: 'Command failed with exit code 128: git commit -S -m 🎉 Base of project with new codebase -m ',
  command: 'git commit -S -m 🎉 Base of project with new codebase -m ',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'error: gpg failed to sign the data\nfatal: failed to write commit object',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by carloscuesta** [comment]
Hey @gensjaak 

I'm pretty sure this is not related with gitmoji-cli. Did you tried to commit without the cli to see If you have the same error ?

Try this:

```
git commit -S -m 🎉 Base of project with new codebase -m
```
