### ISSUE TITLE
can not use with lerna publish

### ISSUE THREAD

**Issue by JiangWeixian** [carloscuesta/gitmoji-cli#335]
Hello @carloscuesta!

if git repo init with lerna, i can't use `lerna publish`

Issue:

to make `lerna publish` work again

- i have to `gitmoji -r`
- then use `lerna publish` 

**OS**: macos
**gitmoji-cli -v**: 3.2.3
**Node version**: 12.4.1

```
lerna info execute Skipping releases
lerna ERR! Error: Command failed: git commit -m v0.0.1
? Choose a gitmoji: 🎨  - Improving structure / format of the code.
? Enter the scope of current changes:
? Enter the commit title [0/48]:
lerna ERR! >> Enter a valid commit title
lerna ERR!     at makeError (/Users/jiangwei/Documents/personal/use-rematch/node_modules/execa/index.js:174:9)
lerna ERR!     at /Users/jiangwei/Documents/personal/use-rematch/node_modules/execa/index.js:278:16
lerna ERR!     at processTicksAndRejections (internal/process/task_queues.js:94:5)
lerna ERR! Error: Command failed: git commit -m v0.0.1
? Choose a gitmoji: 🎨  - Improving structure / format of the code.
? Enter the scope of current changes:
? Enter the commit title [0/48]:
lerna ERR! >> Enter a valid commit title
lerna ERR!     at makeError (/Users/jiangwei/Documents/personal/use-rematch/node_modules/execa/index.js:174:9)
lerna ERR!     at /Users/jiangwei/Documents/personal/use-rematch/node_modules/execa/index.js:278:16
lerna ERR!     at processTicksAndRejections (internal/process/task_queues.js:94:5)
lerna ERR! lerna Command failed: git commit -m v0.0.1
? Choose a gitmoji: 🎨  - Improving structure / format of the code.
? Enter the scope of current changes:
? Enter the commit title [0/48]:
lerna ERR! lerna >> Enter a valid commit title
```

**Comment by JiangWeixian** [comment]
same error with np - https://www.npmjs.com/package/np

**Comment by carloscuesta** [comment]
Hey @JiangWeixian can you provide a reproduction repository ?

Thanks

**Comment by carloscuesta** [comment]
As you can see on the console, the gitmoji-cli is prompting you the following error: 

```
lerna ERR! lerna >> Enter a valid commit title
```

```
lerna ERR! >> Enter a valid commit title
```

You should provide right values for those options

That's the problem!
