### ISSUE TITLE
"failed, reason: self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by Zylvian** [carloscuesta/gitmoji-cli#403]
Hello @carloscuesta!

Issue:
```gitmoji -c``` not working because of self-signed certificate in certificate chain.

**OS**: Windows
**gitmoji-cli -v**: 3.2.6
**Node version**:12.18.1

**Error Message**:

```
× Error: FetchError: request to https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json failed, reason: self signed certificate in certificate chain
TypeError: Cannot read property 'map' of undefined
    at Object.source (C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\lib\commands\commit\prompts.js:27:73)
    at AutocompletePrompt.search (C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\index.js:177:32)
    at AutocompletePrompt._run (C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\index.js:65:10)
    at C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\node_modules\inquirer\lib\prompts\base.js:60:12
    at new Promise (<anonymous>)
    at AutocompletePrompt.run (C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\node_modules\inquirer\lib\prompts\base.js:59:12)
    at C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\node_modules\inquirer\lib\ui\prompt.js:98:27
    at Observable._subscribe (C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\node_modules\rxjs\internal\observable\defer.js:10:21)
    at Observable._trySubscribe (C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\jw10679\AppData\Roaming\npm\node_modules\gitmoji-cli\node_modules\rxjs\internal\Observable.js:30:22)

```

**Comment by carloscuesta** [comment]
Hey I don't think this issue is related with the cli itself. Seems you're having trouble to connect to `https://raw.githubusercontent.com`

Can you reproduce the problem again ?

If the answer is no, then it was a temporary GitHub problem.

Thanks!
