### ISSUE TITLE
failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by KimYangOfCat** [carloscuesta/gitmoji-cli#518]
Hello @carloscuesta!

Issue:

`gitmoji -c` not working because of `read ECONNRESET`.I don’t know if it’s my network problem

**OS**: macOS 11.1
**gitmoji -v**:V3.2.16
**Node version**:v15.4.0

**Error Message**:

```bash
 gitmoji -c
✖ Error: FetchError: request to https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json failed, reason: read ECONNRESET
TypeError: Cannot read property 'map' of undefined
    at Object.source (/usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/lib/commands/commit/prompts.js:34:75)
    at AutocompletePrompt.search (/usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/node_modules/inquirer-autocomplete-prompt/index.js:220:29)
    at AutocompletePrompt._run (/usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/node_modules/inquirer-autocomplete-prompt/index.js:68:10)
    at /usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/node_modules/inquirer/lib/prompts/base.js:60:12
    at new Promise (<anonymous>)
    at AutocompletePrompt.run (/usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/node_modules/inquirer/lib/prompts/base.js:59:12)
    at /usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/node_modules/inquirer/lib/ui/prompt.js:104:12
    at Observable._subscribe (/usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/node_modules/rxjs/internal/observable/defer.js:10:21)
    at Observable._trySubscribe (/usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/usr/local/Cellar/gitmoji/3.2.16/libexec/lib/node_modules/gitmoji-cli/node_modules/rxjs/internal/Observable.js:30:22)
```

**Comment by carloscuesta** [comment]
Hello @KimYangOfCat 

As you point this is a network problem, can you try to access the following URL with your browser?

`https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json`

If you can't access to it, then it might be related to #49 #224

Thanks for opening the issue!

**Comment by KimYangOfCat** [comment]
> Hello @KimYangOfCat
> 
> As you point this is a network problem, can you try to access the following URL with your browser?
> 
> `https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json`
> 
> If you can't access to it, then it might be related to #49 #224
> 
> Thanks for opening the issue!

Hello @carloscuesta 
I can access the URL with my browser.
`https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json`
I have seen these issue，and I have tried some  solutions in   #49 #224, but it still   can't work. I realy want to know why?

**Comment by carloscuesta** [comment]
That's strange, are you using any network proxy?

**Comment by KimYangOfCat** [comment]
> That's strange, are you using any network proxy?

Yes,I'm in china ,so I need to use network proxy to access out network

**Comment by Fatpandac** [comment]
> > That's strange, are you using any network proxy?
> 
> Hello @carloscuesta
> Yes,I'm in china ,so I need to use network proxy to access out network

gitmoji 需要单独设置 proxy 吗？还是直接使用系统设置
