### ISSUE TITLE
⭕ Interface request error

### ISSUE THREAD

**Issue by spark0829** [carloscuesta/gitmoji-cli#637]
Hello @carloscuesta!

Issue: Interface request error

**OS**: macOS BigSur 11.4
**gitmoji -v**: 4.1.0
**Node version**: 14.17.1

**Error Message**:
```
Error: FetchError: request to https://gitmoji.dev/api/gitmojis failed, reason: connect ECONNREFUSED 76.76.21.21:443
TypeError: Cannot read property 'forEach' of undefined
    at printEmojis (/Users/spark/.nvm/versions/node/v14.17.1/lib/node_modules/gitmoji-cli/lib/utils/printEmojis.js:13:19)
    at /Users/spark/.nvm/versions/node/v14.17.1/lib/node_modules/gitmoji-cli/lib/commands/list/index.js:14:88
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by carloscuesta** [comment]
Hey this looks like a connection issue not an issue with the cli thanks!
