### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by toby3d** [carloscuesta/gitmoji-cli#65]
Hello @carloscuesta!

**Issue:** After change default NPM directory (for using installs/tools without `sudo`) I always get same error on any action via `gitmoji`.
**OS**: Linux Mint Mate 18.2 (x64_86)
**gitmoji-cli -v**: ???
**Node version**: v4.2.6
**Error Message**: 
```
$ gitmoji -g
/home/toby3d/.local/lib/node_modules/gitmoji-cli/src/gitmoji.js:16
class GitmojiCli {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/toby3d/.local/lib/node_modules/gitmoji-cli/cli.js:7:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by carloscuesta** [comment]
Hey @toby3d this is due to your `NODE_VERSION` **v4.2.6** does not support the class keyword

**Comment by toby3d** [comment]
@carloscuesta Oops, you're right. :no_mouth:

**Comment by carloscuesta** [comment]
No problem! Maybe we should add this to the docs 😄

**Comment by zwkcoding** [comment]
How to solve it if `NODE_VERSION` v4.2.6 ?

**Comment by carloscuesta** [comment]
Updating your `NODE_VERSION` to the LTS @zwkcoding

**Comment by carloscuesta** [comment]
On the next update, `gitmoji-cli` will not be installed if you don't have the minimum needed `NODE_VERSION` installed.

See https://github.com/carloscuesta/gitmoji-cli/commit/02e091cebddf2fc2e67bf7ac66ec1906ac967603
