### ISSUE TITLE
gitmoji 4.4.0 test failure

### ISSUE THREAD

**Issue by chenrui333** [carloscuesta/gitmoji-cli#658]
Issue:

**OS**: macOS
**gitmoji -v**: 4.4.0
**Node version**: 16.6.1

**Error Message**:

```
$ /usr/local/Cellar/gitmoji/4.4.0/bin/gitmoji --search bug
Error: ENOENT: no such file or directory, open '/Users/rchen/.gitmoji/gitmojis.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.getEmojis (/usr/local/Cellar/gitmoji/4.4.0/libexec/lib/node_modules/gitmoji-cli/lib/utils/emojisCache.js:38:49)
    at getEmojis (/usr/local/Cellar/gitmoji/4.4.0/libexec/lib/node_modules/gitmoji-cli/lib/utils/getEmojis.js:23:54)
    at Object.search (/usr/local/Cellar/gitmoji/4.4.0/libexec/lib/node_modules/gitmoji-cli/lib/commands/search/index.js:17:33)
    at /usr/local/Cellar/gitmoji/4.4.0/libexec/lib/node_modules/gitmoji-cli/lib/cli.js:90:75
    at Array.map (<anonymous>)
    at Object.search (/usr/local/Cellar/gitmoji/4.4.0/libexec/lib/node_modules/gitmoji-cli/lib/cli.js:90:44)
    at findGitmojiCommand (/usr/local/Cellar/gitmoji/4.4.0/libexec/lib/node_modules/gitmoji-cli/lib/utils/findGitmojiCommand.js:33:53)
    at Object.<anonymous> (/usr/local/Cellar/gitmoji/4.4.0/libexec/lib/node_modules/gitmoji-cli/lib/cli.js:94:33) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/rchen/.gitmoji/gitmojis.json'
}
```

relates to https://github.com/Homebrew/homebrew-core/pull/82672

cc @carloscuesta!

**Comment by carloscuesta** [comment]
Thanks for opening the issue! I can reproduce it when I have no cache, taking a look into it 😊

**Comment by chenrui333** [comment]
Nice, thanks for the quick turnaround.

**Comment by carloscuesta** [comment]
Published 🎉
